name: GitHub Actions dev
run-name: Dev updated
on:
  push:
    branches: [dev]
jobs:
  run:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm ci
        env:
          REACT_APP_WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

      - name: Tests
        run: npm run test

      - name: Build
        run: npm run build-git

      - name: Create dev Artifacts 
        uses: actions/upload-artifact@v1
        with:
          name: dev
          path: build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-page-preview
          clean: true
          folder: build
          target-folder: build/dev
